stages:
  - test
  - deploy

sast: # override sast setting
  variables:
    SAST_EXCLUDED_ANALYZERS: brakeman, eslint, flawfinder, gosec, kubesec, nodejs-scan,
      phpcs-security-audit, pmd-apex, security-code-scan, sobelow, spotbugs
  stage: test

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

variables:
  GITLAB_ADVANCED_SAST_ENABLED: 'true'

# DEPLOY
deploy_job:
  stage: deploy
  image: alpine:latest
  script:
    - apk add --no-cache openssh-client
    - echo "$SSH_PRIVATE_KEY" > private_key
    - chmod 600 private_key
    - ssh -i private_key -o StrictHostKeyChecking=no $SSH_USER@$SSH_REMOTE -p $SSH_PORT \
      "cd '$DEPLOY_DIR' \
      && git pull origin origawa \
      && docker compose up --build -d \
      && sleep 5 && netstat -tuln | grep ':6666'"
  when: manual
  rules:
    - if: $CI_COMMIT_BRANCH
